### PR TITLE
Error handling of rare events: t_start==t_end

### PR DESCRIPTION
**Pull request by shinaoka**
Added error handing for rare cases of inserting a null segment

### CODE REVIEW

**Comment by mwallerb** [comment]
@shinaoka Just a comment on this: we hit a very similar problem a while back with w2dynamics.

We observed that time collisions (which are about twice as likely as null segments) are not rare as you would expect them to be: instead of every `2**52 / kmean` steps, we hit them every `2**31 / kmean` steps, where `kmean` is the mean expansion order, which meant that longer simulations crashed frequently.  The reason was that the default Mersenne twister only yields 32 bits, which is then blown up to a double magnitude of 53 bits.

One simple way to fix this in a segment code is to move to a 64-bit PRNG.  This makes it superunlikely to hit this, even for huge simulations.  Might be a better option than to just crash.  But of course it depends on your exact requirements.

**Comment by shinaoka** [comment]
Agreed. This is not rare.
@egull 
What do you think?
Do we really need a 64-bit PRNG?

**Comment by mwallerb** [comment]
If you're worried about performance of the PRNG, you can do something else: whenever the segment length is zero or there is a collision of segment endpoints, you disambiguate by adding `rand[0,1)/2**32` to the random number. This is a little trickier to implement and debug.

What we did in the end is to introduce a "same-time operator order", i.e., the operators are ordered lexicographically by a tuple `(tau, i)`, where `tau` is the imaginary time and `i` is a number from 0 upwards.  This works well for CT-HYB/worm codes, because we frequently need operators (observables) at the same point in imaginary time.

**Comment by egull** [comment]
What we did in previous codes is just detect the collision and reject the move if there was one. These collisions may be frequent (every couple of minutes if you're unlucky) but the complexity for allowing such configurations is  high. So I like your first solution of just ignoring them.

**Comment by shinaoka** [comment]
Could you check the diff and marge the PR if OK?

Markus, thank you for the suggestion!
I did not know that the default Mersenne twister only yields only 32 bits...
But, the resolution is enough for our practical use.

**Comment by egull** [comment]
Done and merged.

Emanuel

**Pull request merged**
